kind: pipeline
name: default

steps:
- name: Make semi-static build with pyinstaller (NOT actually static)
  image: python:latest
  commands:
  - git apply docker.patch
  - apt-get update
  - apt-get install binutils -y
  - pip install pyinstaller
  - cd /drone/src && pip install -r requirements.txt && pyinstaller main.py
  - chmod 777 /drone/src/dist/main/main
  - cd /drone/src/dist/main && tar cvfz /drone/src/AlwaysDungeons.tar.gz *  
- name: build and publish
  image: plugins/docker
  pull: always
  settings:
    repo: askiiart/discord-always-dungeons
    tags: latest
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password